### ISSUE TITLE
Transfer repository and npm access

### ISSUE THREAD

**Issue by daffl** [feathersjs-ecosystem/feathers-couchbase#60]
Hi Frank!

I got commissioned by [a Feathers sponsor](https://fortify.pro/) to implement a Couchbase adapter that is compatible with the latest versions of Couchbase, Feathers and [the Feathers database syntax](https://docs.feathersjs.com/api/databases/common.html). They agreed to release it as open source and I was wondering if you'd agree with moving this repository into [feathersjs-ecosystem](https://github.com/feathersjs-ecosystem/) and adding me to npm so that we can have a single official version of a Couchbase adapter. If you have different plans, that's totally fine but I'd thought I ask.

**Comment by frank-dspeed** [comment]
@daffl you know i love working with you i love the project in general and sure we can work together on that i would say the most easy path is that you fork this into feathers. as i have not the access to the https://github.com/feathersjs-ecosystem/ group to create repos there. i want to note that there are 2 diffrent feathers-couchbase projects it exists also a so called ottoman version that will be maybe even prefered https://github.com/direktspeed/feathers-couchbase-odm or we can merge them both 

i would love to directly talk to you next week via zoom or any other channel that you prefer so that i can update you what are the edge cases with couchbase and this implementation and how we could progress.

**Comment by frank-dspeed** [comment]
@daffl added you as admin for this repo

**Comment by daffl** [comment]
Thank you! I can add you to the ecosystem organization no problem if you are interested in transferring it over. Happy to have a call as well. Can you send me a private message in Slack with a time that would work for you? You can find the code I've been working on at https://github.com/daffl/feathers-couchbase.

**Comment by frank-dspeed** [comment]
@daffl yes please add me there as feathers-couchbase gets used in vending machines :)

**Comment by daffl** [comment]
I am planning on putting up a PR this week for the latest version (just trying to get automated tests working) so you can review. Would you be able to [add me to the repository on npm](https://www.npmjs.com/package/feathers-couchbase) as well (this can usually be done in the "Settings" tab when you are logged in)?

**Comment by frank-dspeed** [comment]
@daffl that should be already done isn't it ? i will recheck that but i think i already did that.

**Comment by daffl** [comment]
My bad you are absolutely right, thanks!

**Comment by frank-dspeed** [comment]
@daffl your always welcome
